language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
env:
  global:
    - secure: "nUtPupWs/af2Qvpa/7BwnT3GdKgWi457gQGM197SQjrvbotgYS83iXFGLq2d6wuEsMWi0CcNy9sQ452LzeRRge2Vv8q2Ix45gNicWZF/lxmoscr7sjWrhYJnlH4UKxEFYecu44TEmfeb1Kq4/RVMGSz/T9SfNq8dA5hqQ7MEqIwNeGuD38LCLq4WxpeJ2M/+ue9xVPPZpieNEbUstWUWgaHFOuF/F3bZmqkh9N8W+srJu4xz7EQ6cFlnj2d4xVhdcGjvwEVsZLg4mDGSPcZIlU7nEKBWJtfKt2oGuHP3uXxAwkTitchcjmCdWsj8AFx0IWpmASJmWcF89wZOUBLOlA8QzV0wAirwABELSmjnHnmqYaSU89eICoVcIe3nQkvuLhQ6dNbPReKraEm7vwlU3WFF0WzJodRKoNIT8yPOR3jDKUxAgEEruVOJrMt4jOlL8HnUoWrsV/5p6TOiwdJNvRk1w9MCQwtfQYOWYSk4EzwTwlpxT5ib3wZeHwonZ/6xqurWfSFUpzmqXS43f8GW0z1131gZcm+xMS8mi0B9DYbHT0HIBX/xpIMtTqLN+NM//q9r0bmqxMKCU3NQ1nfszFjmiOWjl1BRypTkze/YsJ87bfhjVsDD7ioAZGONBpAq/e9sIEe6j0D6HQy8upyeXSqIny/zYSCU+mrcAEasrL0="
    - secure: "n6OwJiaN8atLuOi/GVwAYhTJ18erM94v6rmi9dNJxMYe06nNYheudboTP2iTPhHYPyi4yjWJMobw2JU3OjsZEiRuD5OezbL/hR2oW7XuD7H0Ng0hKp08f/+RQPNQbimTsaQTuQ3R9vfuBgdN4FRKWf8r8xpsENgnruTOlHU/Ag3SDwkTVKZ0ShmPL1cYjoRkjGCsIJSSvHYuT/KGz/opposbuRsy0HcW1s2k6gNvo70I4ooJO8IPpVkErEH+/IYCaokIgQnH56czfI2Q+EQ7PIp0apU/XIlpWzEF+yIES4O9Jbv6McQW50xpbhwT9gzx05unQmdJhSH6SCAW9pFqhqk12sVGVFgwSwVbKpqOI72fdsaFdBKiE5QfrIZK1ez2F1CCAMQh9q06DhGEtj3G7YbhCGvb3181b+Hk+fKl75T4Myu5mo2sq4fRIhR0z6eTxtodncVRBtzi/brVIZMwV5IJqiWryUpb2SHW8MlavINfjritvV/4Ncyc8I6mBKgskoogrAtuuqz6m91jf3nJHwEv+pjmSew4vaOlxwf/za4EvwUeHu6J6qjzN93UrfNbsNNcK0Bog2VpOUtqlfBYeqFnvWwQZtpw/xoLS+8Um8FlpTLE/K8PGbiirjbyY4Kgj3F8sGfmkAmjEiUFdzGFJ+qc9LuMA+OLh6Lgu+TBWoo="
    - secure: "kOA++zCNMQ6rIWeKaTZkGdc9H91YEiePaXW1nvGNAYnKqaw+jIXYmDWKdKTxfE4B2NwDeaAdjpUsni1KpbU10ItxlKTOe5r8vysOg53fv3bOAYk78x0Y58WbcJhLSm+y5gxZP8mZCbthM1mibsc6TcSHpemz1Ozs2loMcgOC7YNoPLdFdFVHC/PW7iqIhxqNOTOx5yvLiZbcBiXBXLVoiViy6sLJADE0Z2ct+bj1wU+WzFYNs+/jum8bJgiEP9kGepbh8s6RdNI8au2JfARSATVh5eUlckDG/ie1zZFGF/wsDJcRyjmxfT95izbR4ISD0PBymh24gDrgdcgH1Lb3G1ktG/wCHQluTqfxjsiMTeQ7eV+R0CUKDmRb2HNwsHx6KaKyWG/F58xksmZIjjsbe7tjK1ipNZbaul2KAjBvssSzaexnpRQ3q6kYFLlr7S2psZLFwb95I1+KzrZkBSPoxRo4iTfZLusjP/dCmpL/OGdJQ5XVzIHxX62bPPtsUSlEUSyRLrtahKWmd6gC6vCLSpBAaTFUqW+FV9wuOWj1HPRnbQkDVZLoFoUeVddZn2Le5ArW7hc1eBXG8yxOLl210rRV3sm2sKhR/SPKn0lfgrdhWQ9CjHFRvv/8aGaKQBY+4ICcP5f40wLkP+4rVwH8ULK6/suQiq2UI2WrhuSPyHg="
    - secure: "GqSfPB7TxvN/vKa6pdFB1QgTAW2neA/BHhkpnJGwPvHvic6toQOJPLVpdj1VlSsmzLbg0x9igzrWL993VoLOO/TPdc0nOubgGje2fNLMKyPO57B+Uou9Ir64ElJSOVHEChDlJ7nzPzZs3HW8khSCj9Xwrs5rLgD6syLDEhTp9PU5PAVbsM4AeuBbbvacXc0TB88bDnZZoTZEGFm3l1yYz839+gSgnj5kEtT7OCTuF9JtiKGnViIigdiGPrWx4Ywt9xNWhhvP7OqGwsrc3NwGixmreCO0YztCUc3gnF9VoUx4WzcQAH0i+i2iJXlS1M7LCjyz6qvGO2zJSKtux3fTv+XtnFG72um7KZNUf915ioFbrgq47D9q+1TtsJ1YWN1TWKiWqEF7HE5mDWwpdH4LgMmjhJWZG/hLBc6Aih20JZOz2SHdz1LeVumTZG87SytaDtTomSI/vsfR5EqRYA7azaCBO5KnY+UVn8tPAfe4fhakDGGcZY6zc1DhgofJ6TzDIP7zOU4iVa2jY7bmLvSBKrRwPpYVG3ybuxNUNNdh874Wx27WUx3II8aj9hAPo+GgngLGvYYHLKZGrKhPLZkHrTqs74xjrJtwzP5O/AVNOcXr1b6rNwGE0fhicH0XC6tSh5gakTy7zvt5rH1J6LWLgIihNqjEIn1SigmjXaLj9EQ="

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - chmod a+x ./cd/before-deploy.sh
  - chmod a+x ./cd/deploy.sh
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh