language: java
jdk:
  - oraclejdk8
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
env:
  global:
    - secure: "YyCETggJ2JnhpJoF1VJK8vo7g0UCKFWdpocqlNP/dOirjlkFBlg9SQQaqYDJkaJt/zQ6kp+NRFfDQjuKDEDUHUGzpWZlIKTi17Q3MWUEOROHJT0GsrYZVnN26w3Y5GsihWS+E2oPi66+vx1pGnZFd7ng+vVWMoiv6yNmKvgv1xRN6J3Lc+u3t1O4tYWqwGZ2oXFB0iiMepx6aQj1SpXVxaanefsJ1GJB6IfoM70IL0kZjtwYNK+Gy07CeTGis6IHnENRTUDRIdOE5aoDIYEyp3fXdbXZxdJcdJswMQDKZzRx1Kkl5auUeBmnhtTtU/MwjGi6Juij3Cer8Kc9lvL71FAi7aP7y20ub2sAHwvOnUfXbVw4cEWsMaKACj5dYLL5QFbTfbzWIs0NwbV6GTuAcLYTCzx8wLfHAx7YxysZ0UOEDZXFNx0pfrTmf8b5DLCZ7ZcsUHx3EwlNcUuW6oK3AxT7jo2mFHhhAfpPKJfh+fpCtuYSjT8PTVKg9bDasGciFFp/XZgIzo5ms+Jr0QRbOjvTwIi/yor2zBR05E35q3zInRBSSGzZHqT0xMYx4ud2JScKJ/WR20RX6ZV1s4zx5XOTHxwGZUur0NJQw3+R3UxGt7vHrvx1bGERJR94S8Q+6PUUs0cPOlxOvfHjP5UPA2yLYxecMac6zFwE2ifpa8g="
    - secure: "k+ligl7DMmXya26KvzBKLxsnGYJUFGZtdmT8TkmwFTGkcrBuEnid/eWNsta7etfpthHbcKiIS51y8UGy5wD31bROR4H5+yLhBbKJ9vexK1RgE6TvfW+HRDvo6xA3ceM9ceSr6dZvP2lSyLqSNLAa6tXqZUVhLDjvW7KOcHvYmAGuN/3eGv1RPwscRFqFZj0NkX4clQUna1n/7mZNVwkZYI+QOW3SEZN19B/xGS8w3heoV/oZoOVnvjpNRSP4UV6Ynf7KfY/HBOgPGvJJBfvwlKpBmHHFgleQnRO0Vwcq5U8YiFs+r/Wt7swhiyY5450stHxttPcNktMhQAf4vFg9wGPry97/nXt/Znp7ZYZ8Hm9jK2arbkXAL88hT4PmkPKJK+XS2GG1+6xzaYsa/CuOYvaaDlp8oekg3rwcEtL5ytpt6iJYmLbrCpk2QdH+EZoO/8FajPYbsRymdlFXHq13h3n7kzGFTm9Q9R0eul2ijYdQT/kYNpFDP9tnfsP80vDImACbJL7F0sDtyXUHDhqThyLel+nk5XJgkLAghUycbPfD0INPljH38dyaaChBRLRuzGSC0XvSWGPxc91zNyuAicNyfl00rLBfUjK7e8LB8b3wF28tb0ChNBSrRS/eg41IPTA3S0aKATHHkRo+aLMhyTvus6U60tZd/3aD+06VglM="
    - secure: "kOA++zCNMQ6rIWeKaTZkGdc9H91YEiePaXW1nvGNAYnKqaw+jIXYmDWKdKTxfE4B2NwDeaAdjpUsni1KpbU10ItxlKTOe5r8vysOg53fv3bOAYk78x0Y58WbcJhLSm+y5gxZP8mZCbthM1mibsc6TcSHpemz1Ozs2loMcgOC7YNoPLdFdFVHC/PW7iqIhxqNOTOx5yvLiZbcBiXBXLVoiViy6sLJADE0Z2ct+bj1wU+WzFYNs+/jum8bJgiEP9kGepbh8s6RdNI8au2JfARSATVh5eUlckDG/ie1zZFGF/wsDJcRyjmxfT95izbR4ISD0PBymh24gDrgdcgH1Lb3G1ktG/wCHQluTqfxjsiMTeQ7eV+R0CUKDmRb2HNwsHx6KaKyWG/F58xksmZIjjsbe7tjK1ipNZbaul2KAjBvssSzaexnpRQ3q6kYFLlr7S2psZLFwb95I1+KzrZkBSPoxRo4iTfZLusjP/dCmpL/OGdJQ5XVzIHxX62bPPtsUSlEUSyRLrtahKWmd6gC6vCLSpBAaTFUqW+FV9wuOWj1HPRnbQkDVZLoFoUeVddZn2Le5ArW7hc1eBXG8yxOLl210rRV3sm2sKhR/SPKn0lfgrdhWQ9CjHFRvv/8aGaKQBY+4ICcP5f40wLkP+4rVwH8ULK6/suQiq2UI2WrhuSPyHg="
    - secure: "GqSfPB7TxvN/vKa6pdFB1QgTAW2neA/BHhkpnJGwPvHvic6toQOJPLVpdj1VlSsmzLbg0x9igzrWL993VoLOO/TPdc0nOubgGje2fNLMKyPO57B+Uou9Ir64ElJSOVHEChDlJ7nzPzZs3HW8khSCj9Xwrs5rLgD6syLDEhTp9PU5PAVbsM4AeuBbbvacXc0TB88bDnZZoTZEGFm3l1yYz839+gSgnj5kEtT7OCTuF9JtiKGnViIigdiGPrWx4Ywt9xNWhhvP7OqGwsrc3NwGixmreCO0YztCUc3gnF9VoUx4WzcQAH0i+i2iJXlS1M7LCjyz6qvGO2zJSKtux3fTv+XtnFG72um7KZNUf915ioFbrgq47D9q+1TtsJ1YWN1TWKiWqEF7HE5mDWwpdH4LgMmjhJWZG/hLBc6Aih20JZOz2SHdz1LeVumTZG87SytaDtTomSI/vsfR5EqRYA7azaCBO5KnY+UVn8tPAfe4fhakDGGcZY6zc1DhgofJ6TzDIP7zOU4iVa2jY7bmLvSBKrRwPpYVG3ybuxNUNNdh874Wx27WUx3II8aj9hAPo+GgngLGvYYHLKZGrKhPLZkHrTqs74xjrJtwzP5O/AVNOcXr1b6rNwGE0fhicH0XC6tSh5gakTy7zvt5rH1J6LWLgIihNqjEIn1SigmjXaLj9EQ="

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - chmod a+x ./cd/before-deploy.sh
  - chmod a+x ./cd/deploy.sh
  - ./cd/before-deploy.sh
  - ./cd/deploy.sh